"""
Seed 400 products into products_update.

Usage:
  python seed_400_products.py

Optional:
  SET CLEAR_EXISTING=1 to wipe products_update before insert.
"""

import os
import sys
import random
from datetime import datetime, timezone
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

MONGO_URL = os.getenv("MONGODB_URL", "").strip()
if not MONGO_URL:
    print("ERROR: MONGODB_URL not set in .env")
    sys.exit(1)

client = MongoClient(MONGO_URL)
db = client["saless"]
products_update = db.products_update

if os.getenv("CLEAR_EXISTING", "").strip() == "1":
    products_update.delete_many({})
    print("Cleared products_update")

CATEGORIES_PRODUCTS = {
    "Food & Beverages": [
        "சோனா மாசூரி அரிசி (Sona Masuri Rice)",
        "பொன்னி அரிசி (Ponni Rice)",
        "பாஸ்மதி அரிசி (Basmati Rice)",
        "மட்டா அரிசி (Matta Rice)",
        "ரவா (Rava)",
        "சோலா (Jowar)",
        "கம்பு (Bajra)",
        "கோதுமை மாவு (Wheat Flour)",
        "அரிசி மாவு (Rice Flour)",
        "மிளகு ரசம் தூள் (Pepper Rasam Powder)",
        "சாம்பார் பொடி (Sambar Powder)",
        "ரசம் பொடி (Rasam Powder)",
        "கரம் மசாலா (Garam Masala)",
        "சீரகம் (Cumin)",
        "பிரியாணி மசாலா (Biryani Masala)",
        "உப்பு (Salt)",
        "பனை வெல்லம் (Palm Jaggery)",
        "சக்கரை (Sugar)",
        "பச்சை பயறு (Green Gram)",
        "துவரம் பருப்பு (Toor Dal)",
        "உளுந்து பருப்பு (Urad Dal)",
        "சீரகச் செவ்வரி (Seeraga Samba Rice)",
        "இட்லி அரிசி (Idli Rice)",
        "பொங்கல் அரிசி (Pongal Rice)",
        "பாசிப்பருப்பு (Moong Dal)",
        "கடலை பருப்பு (Chana Dal)",
        "கருப்பு உளுந்து (Black Urad)",
        "கொண்டைக்கடலை (Chickpea)",
        "காய்ந்த மிளகாய் (Dry Red Chilli)",
        "கடுகு (Mustard Seeds)",
        "தேங்காய் எண்ணெய் (Coconut Oil)",
        "நல்லெண்ணெய் (Gingelly Oil)",
        "சூரியகாந்தி எண்ணெய் (Sunflower Oil)",
        "வேர்கடலை எண்ணெய் (Groundnut Oil)",
        "நெய் (Ghee)",
        "தேங்காய் துருவல் (Desiccated Coconut)",
        "அப்பளம் (Appalam)",
        "மிக்ஸ்சர் (Mixer)",
        "முறுக்கு (Murukku)",
        "ஒமப்பொடி (Omapodi)",
        "பக்கோடா மிக்ஸ் (Pakoda Mix)",
        "இட்லி மாவு (Idli Batter)",
        "தோசை மாவு (Dosa Batter)",
        "புலியோதரை பொடி (Puliyodharai Mix)",
        "லெமன் சாதம் பொடி (Lemon Rice Mix)",
        "வத்தல் குழம்பு பொடி (Vathal Kuzhambu Mix)",
        "கல்யாண ரசம் பொடி (Marriage Rasam Mix)",
        "சிவப்பு மிளகாய் தூள் (Chilli Powder)",
        "மஞ்சள் தூள் (Turmeric Powder)",
        "மல்லி தூள் (Coriander Powder)",
        "சீரக தூள் (Cumin Powder)",
        "பூண்டு (Garlic)",
        "இஞ்சி (Ginger)",
        "பெருங்காயம் (Asafoetida)",
        "தாளிப்புப் பொருள் (Tadka Mix)",
        "பாயசம் மிக்ஸ் (Payasam Mix)",
        "போஹா (Poha)",
        "கடலை மாவு (Besan)",
        "சேவை (Vermicelli)",
        "நூடுல்ஸ் (Noodles)",
        "பாஸ்தா (Pasta)",
        "உருளைக்கிழங்கு மாவு (Potato Starch)",
        "காப்பி தூள் (Coffee Powder)",
        "டீத் தூள் (Tea Powder)",
        "சோயா சாஸ் (Soy Sauce)",
        "மிளகாய் சாஸ் (Chilli Sauce)",
        "தக்காளி சாஸ் (Tomato Sauce)",
        "உலர் மூலிகை தேநீர் (Herbal Tea)",
        "சீனீ (Brown Sugar)",
        "வாழைப்பூ வத்தல் (Banana Flower Chips)",
    ],
    "Vegetables": [
        "வெங்காயம் (Onion)",
        "தக்காளி (Tomato)",
        "உருளைக்கிழங்கு (Potato)",
        "வெள்ளாடை (Carrot)",
        "கீரை (Spinach)",
        "பூக்கோஸ் (Broccoli)",
        "காளான் (Mushroom)",
        "கத்தரிக்காய் (Brinjal)",
        "வெண்டைக்காய் (Okra)",
        "புடலங்காய் (Bottle Gourd)",
        "பீர்க்கங்காய் (Ridge Gourd)",
        "சுரைக்காய் (Ash Gourd)",
        "பாகற்காய் (Bitter Gourd)",
        "பூசணி (Pumpkin)",
        "முட்டைக்கோஸ் (Cabbage)",
        "காலிஃபிளவர் (Cauliflower)",
        "சிவப்பு காப்சிகம் (Red Capsicum)",
        "மஞ்சள் காப்சிகம் (Yellow Capsicum)",
        "பச்சை காப்சிகம் (Green Capsicum)",
        "பீன்ஸ் (Beans)",
        "பச்சை பட்டாணி (Green Peas)",
        "கொத்தவரங்காய் (Cluster Beans)",
        "சேனைக்கிழங்கு (Yam)",
        "சேப்பங்கிழங்கு (Arbi)",
        "முள்ளங்கி (Radish)",
        "சுரக்காய் (Chayote)",
        "செங்கிழங்கு (Sweet Potato)",
        "சோளம் (Corn)",
        "இளநீர் (Tender Coconut)",
        "வாழைப்பழம் மொட்டு (Banana Stem)",
    ],
    "Fruits": [
        "மாம்பழம் (Mango)",
        "வாழைப்பழம் (Banana)",
        "ஆப்பிள் (Apple)",
        "ஆரஞ்சு (Orange)",
        "திராட்சை (Grapes)",
        "கொய்யா (Guava)",
        "சப்போட்டா (Sapota)",
        "சீதாப்பழம் (Custard Apple)",
        "அன்னாசி (Pineapple)",
        "பப்பாளி (Papaya)",
        "தர்பூசணி (Watermelon)",
        "சாத்துக்குடி (Mosambi)",
        "மாதுளை (Pomegranate)",
        "கிவி (Kiwi)",
        "ஸ்ட்ராபெரி (Strawberry)",
        "பேரிக்காய் (Pear)",
        "பிளம் (Plum)",
        "அன்னிப்பழம் (Fig)",
        "நெல்லிக்காய் (Amla)",
        "செமந்தி பழம் (Star Fruit)",
    ],
    "Dairy": [
        "பால் (Milk)",
        "தயிர் (Yogurt)",
        "வெண்ணை (Butter)",
        "பனீர் (Paneer)",
        "மோர் (Buttermilk)",
        "நெய் (Ghee)",
        "சீஸ் (Cheese)",
        "வெண்ணெய் சீஸ் ஸ்பிரெட் (Cheese Spread)",
        "க்ரீம் (Fresh Cream)",
        "லஸ்சி (Lassi)",
    ],
    "Dry Fruits": [
        "முந்திரி (Cashew)",
        "பாதாம் (Almond)",
        "உலர் திராட்சை (Raisins)",
        "பிஸ்தா (Pistachio)",
        "அத்திப்பழம் (Dried Fig)",
        "வால்நட் (Walnut)",
        "தேதிகள் (Dates)",
        "சிங்காக்கொட்டை (Fox Nuts)",
        "மகானி விதை (Chironji)",
    ],
    "Snacks": [
        "சிப்ஸ் (Chips)",
        "க்ரீம் பிஸ்கட் (Cream Biscuits)",
        "மிக்ஸ்சர் (Mixer)",
        "முறுக்கு (Murukku)",
        "சீடா (Sev)",
        "கராசேவை (Kara Sev)",
        "அச்சு முருக்கு (Achu Murukku)",
        "குணுக்கு (Pakoda)",
        "பிரெட் ஸ்டிக்ஸ் (Bread Sticks)",
        "பிஸ்கட் (Biscuits)",
        "சாக்லேட் (Chocolate)",
        "ஜெல்லி (Jelly)",
    ],
    "Bakery": [
        "ப்ரெட் (Bread)",
        "பன் (Bun)",
        "கேக் (Cake)",
        "மஃபின் (Muffin)",
        "பிஸ்கட் (Biscuits)",
        "க்ரோசான் (Croissant)",
    ],
    "Beverages": [
        "காப்பி (Coffee)",
        "தேநீர் (Tea)",
        "பழச்சாறு (Fruit Juice)",
        "எலுமிச்சை சாறு (Lime Juice)",
        "ஆரஞ்சு சாறு (Orange Juice)",
        "மாதுளை சாறு (Pomegranate Juice)",
        "மில்க் ஷேக் (Milkshake)",
        "சோடா (Soda)",
        "மினரல் வாட்டர் (Mineral Water)",
    ],
    "Personal Care": [
        "சோப்பு (Soap)",
        "ஷாம்பு (Shampoo)",
        "டூத் பேஸ்ட் (Toothpaste)",
        "டூத் பிரஷ் (Toothbrush)",
        "ஹேர் ஆயில் (Hair Oil)",
        "பாடி லோஷன் (Body Lotion)",
        "க்ரீம் (Face Cream)",
        "குளியல் ஜெல் (Shower Gel)",
        "சேனிட்டரி நாப்கின் (Sanitary Pads)",
        "சான்ிடைஸர் (Sanitizer)",
    ],
    "Household": [
        "டிட்டர்ஜென்ட் (Detergent)",
        "பாத்திரம் கழுவும் திரவம் (Dishwash Liquid)",
        "மாடி கிளீனர் (Floor Cleaner)",
        "குளிரூட்டி வாசனை (Room Freshener)",
        "குப்பை பைகள் (Garbage Bags)",
        "பேப்பர் டிஷ்யூ (Tissue Paper)",
        "பளபளப்பு துணி (Cleaning Cloth)",
        "பிளீச் (Bleach)",
        "பைரிட்ரின் (Insect Repellent)",
        "பாதுகாப்பு கையுறை (Gloves)",
    ],
    "Spices": [
        "மிளகு (Pepper)",
        "மஞ்சள் (Turmeric)",
        "மல்லி (Coriander)",
        "சீரகம் (Cumin)",
        "வெந்தயம் (Fenugreek)",
        "சோம்பு (Fennel)",
        "இலவங்கப்பட்டை (Cinnamon)",
        "லவங்கம் (Clove)",
        "ஏலக்காய் (Cardamom)",
        "ஜாதிக்காய் (Nutmeg)",
        "அஜ்வைன் (Ajwain)",
        "கசக்கசா (Poppy Seeds)",
        "பிரியாணி மசாலா (Biryani Masala)",
        "சாட் மசாலா (Chaat Masala)",
        "மீன் மசாலா (Fish Masala)",
        "சிக்கன் மசாலா (Chicken Masala)",
        "மட்டன் மசாலா (Mutton Masala)",
    ],
}

def make_name(base, idx):
    return f"{base} Pack {idx:03d}"

existing = set(p["name"] for p in products_update.find({}, {"name": 1}))
products = []
now = datetime.now(timezone.utc)
target = 400

expanded = []
for category, names in CATEGORIES_PRODUCTS.items():
    for name in names:
        expanded.append((name, category))

if len(expanded) < target:
    extras = [
        "மடிக்கால் நெய் (Pure Ghee)",
        "கோவை சீனீ (Coimbatore Sugar)",
        "மிளகாய் ஊறுகாய் (Chilli Pickle)",
        "எலுமிச்சை ஊறுகாய் (Lemon Pickle)",
        "மாம்பழ ஊறுகாய் (Mango Pickle)",
        "இஞ்சி பூண்டு விழுது (Ginger Garlic Paste)",
        "இட்லி பொடி (Idli Podi)",
        "சுட்ட புட்டு மாவு (Puttu Flour)",
        "அரிசி சேமியா (Rice Vermicelli)",
        "செவ்வரி அரிசி (Seeraga Samba)",
        "அத்திப்பழம் பாக்கெட் (Fig Pack)",
        "தேன் (Honey)",
        "பனை வெல்லம் பவுடர் (Palm Jaggery Powder)",
        "பசலைகீரை (Palak)",
        "வெள்ளரி (Cucumber)",
        "மிளகாய் (Green Chilli)",
        "கொத்தமல்லி (Coriander Leaves)",
        "புதினா (Mint Leaves)",
        "கறிவேப்பிலை (Curry Leaves)",
        "முருங்கைக்காய் (Drumstick)",
        "சுரைக்காய் விதை (Pumpkin Seeds)",
        "சூரியகாந்தி விதை (Sunflower Seeds)",
        "வேர்க்கடலை (Peanut)",
        "கடலை சட்னி பவுடர் (Chutney Powder)",
        "செம்பருத்தி ஆயில் (Hibiscus Oil)",
        "மிளகு எண்ணெய் (Pepper Oil)",
        "கடுக்காய் பொடி (Haritaki Powder)",
        "நாட்டு சக்கரை (Country Sugar)",
        "துட்டு வெல்லம் (Jaggery Cubes)",
        "நெல்லிக்காய் மிட்டாய் (Amla Candy)",
        "வாழைப்பழ சிப்ஸ் (Banana Chips)",
        "வெட்டிவேர் பவுடர் (Vetiver Powder)",
        "பாரம்பரிய காபி (Filter Coffee)",
        "மிலகா காபி (Chicory Coffee)",
        "சர்பத் (Sharbat)",
        "சீரியல் மிக்ஸ் (Cereal Mix)",
        "குழம்பு மிளகாய் (Kuzhambu Chilli)",
        "புளி (Tamarind)",
        "புளி பேஸ்ட் (Tamarind Paste)",
        "கோவை வெங்காயம் (Shallots)",
        "அசைவில்லா வெண்ணெய் (Dairy Free Butter)",
        "அயோடைஸ் உப்பு (Iodized Salt)",
        "கடலை மிட்டாய் (Peanut Candy)",
        "எலுமிச்சை மிட்டாய் (Lemon Candy)",
        "இஞ்சித் தேநீர் (Ginger Tea)",
        "துளசி தேநீர் (Tulsi Tea)",
        "குக்கிங் க்ரீம் (Cooking Cream)",
        "கோவா பன் (Goa Bun)",
        "கோகோ பவுடர் (Cocoa Powder)",
        "வனிலா எசன்ஸ் (Vanilla Essence)",
        "சோயா பீன் (Soybean)",
        "சோயா துண்டுகள் (Soya Chunks)",
        "சோயா பால் (Soy Milk)",
        "ரேஷன் அரிசி (Ration Rice)",
        "மாவு மிளகாய் (Chilli Flakes)",
        "ஒரிகானோ (Oregano)",
        "பிசா மசாலா (Pizza Seasoning)",
        "பாஸ்தா சாஸ் (Pasta Sauce)",
        "சீஸ் ஸ்லைஸ் (Cheese Slices)",
        "மேயோனைஸ் (Mayonnaise)",
        "டோமேட்டோ கேச்சப் (Ketchup)",
        "ஸ்ட்ராபெரி ஜாம் (Strawberry Jam)",
        "மிக்ஸ் ஃப்ரூட் ஜாம் (Mixed Fruit Jam)",
        "தேன் எலுமிச்சை (Honey Lemon)",
        "சீரகம் நீர் (Cumin Water)",
        "பழ வகை நெக்டர் (Fruit Nectar)",
        "மில்க் ஷேக் மिक्स் (Milkshake Mix)",
        "பால் புட்டு (Milk Puttu)",
        "ரவை இட்லி மிக்ஸ் (Rava Idli Mix)",
        "உப்புமா மிக்ஸ் (Upma Mix)",
        "மெஸூர் பாக் (Mysore Pak)",
        "பொங்கல் மிக்ஸ் (Pongal Mix)",
        "சூப் மிக்ஸ் (Soup Mix)",
        "மக்னி மிக்ஸ் (Maggi Mix)",
        "நூடுல்ஸ் மசாலா (Noodle Masala)",
        "புளியோதரை பேஸ்ட் (Puliyodharai Paste)",
        "தக்காளி தொக்கூ (Tomato Thokku)",
        "இஞ்சி தொக்கூ (Ginger Thokku)",
        "மாங்காய் தொக்கூ (Mango Thokku)",
        "நெல்லிக்காய் உருண்டை (Amla Balls)",
        "சீனி அப்பளம் (Sweet Appalam)",
        "புளிப்பு அப்பளம் (Spicy Appalam)",
        "சர்க்கரை எறிகட்டி (Sugar Cubes)",
        "சீரக மிட்டாய் (Cumin Candy)",
        "வெட்டிவேர் தண்ணீர் (Vetiver Water)",
        "ரோஸ் வாட்டர் (Rose Water)",
        "ரோஸ் மில்க் (Rose Milk)",
        "பாதாம் பால் (Badam Milk)",
        "ஜீரா சோடா (Jeera Soda)",
        "மிந்தா (Mint Syrup)",
        "சர்க்கரை பாகு (Sugar Syrup)",
        "பனீர் டிக்கா (Paneer Tikka Ready)",
        "பட்டர் சிக்கன் சாஸ் (Butter Chicken Sauce)",
        "சிக்கன் கிரேவி மிக்ஸ் (Chicken Gravy Mix)",
        "மட்டன் கிரேவி மிக்ஸ் (Mutton Gravy Mix)",
        "மீன் ஃப்ரை மசாலா (Fish Fry Masala)",
        "பிரியாணி அரிசி (Biryani Rice)",
        "பிரியாணி மசாலா பேஸ்ட் (Biryani Paste)",
        "சிறுதானிய மாவு (Millet Flour)",
        "ராகி மாவு (Ragi Flour)",
        "சாமை (Little Millet)",
        "வரகு (Kodo Millet)",
        "தினை (Foxtail Millet)",
        "குதிரைவாலி (Barnyard Millet)",
        "பனீர் மசாலா (Paneer Masala)",
        "கோதுமை சேமியா (Wheat Vermicelli)",
        "பாலியல் கஞ்சி (Milk Porridge)",
        "கோதுமை ரோட்டி (Wheat Roti)",
        "சப்பாத்தி மாவு (Chapati Flour)",
        "பராத்தா (Paratha)",
        "நான் (Naan)",
        "பிடா (Pita Bread)",
        "காப்பி பிஸ்கட் (Coffee Biscuits)",
        "மருந்து சோப்பு (Medicinal Soap)",
        "ஹெர்பல் ஷாம்பு (Herbal Shampoo)",
        "ஹேர் கண்டிஷனர் (Hair Conditioner)",
        "டால்கம் பவுடர் (Talcum Powder)",
        "சன்ஸ்கிரீன் (Sunscreen)",
        "மவுத் வாஷ் (Mouth Wash)",
        "கைக்கழுவும் திரவம் (Hand Wash)",
        "ஹேர் கலர் (Hair Color)",
        "சரும கிரீம் (Skin Cream)",
        "கண் மேகப் (Eye Makeup)",
        "லிப் பாம் (Lip Balm)",
        "அரோமா மெழுகுவர்த்தி (Aroma Candle)",
        "மெழுகுவர்த்தி (Candle)",
        "பூஜை எண்ணெய் (Pooja Oil)",
        "அகர்பத்தி (Incense Sticks)",
        "கற்பூரம் (Camphor)",
        "பூஜை குங்குமம் (Kumkum)",
        "சந்தனம் பொடி (Sandal Powder)",
        "பூஜை தட்டு (Pooja Plate)",
        "கிருமி நாசினி (Disinfectant)",
        "தூசி துடைப்பான் (Duster)",
        "மூடி பைகள் (Ziplock Bags)",
        "தூசி குடம் (Dustbin)",
        "கைக்குடம் (Hand Towel)",
        "முகத்துணி (Face Towel)",
        "படுக்கைத் தாள் (Bed Sheet)",
        "பாத்திரத் தூள் (Dishwash Powder)",
        "நெயில் கிளீனர் (Nail Cleaner)",
        "கிச்சன் ஸ்பொஞ்ச் (Kitchen Sponge)",
        "தண்ணீர் பாட்டில் (Water Bottle)",
        "ஸ்டீல் டிபின் (Steel Tiffin)",
        "பிளாஸ்டிக் டிபின் (Plastic Tiffin)",
        "அரிசி கூழ் (Rice Porridge)",
        "அவல் (Aval)",
        "அவல் மிக்ஸ் (Aval Mix)",
        "பாயசம் சக்கு (Payasam Sago)",
        "கேழ்வரகு (Ragi)",
        "செரியோஸ் (Cereal)",
        "ஓட்ஸ் (Oats)",
        "மூஸ்லி (Muesli)",
        "கோர்ன்ஃபிளேக்ஸ் (Cornflakes)",
        "உலர் பழ சீரியல் (Dry Fruit Cereal)",
        "கஷாயம் பொடி (Herbal Kashayam)",
        "நாட்டு மருந்து கஞ்சி (Herbal Porridge)",
        "நெல்லிக்காய் ஜூஸ் (Amla Juice)",
        "ஆப்பிள் சைடர் (Apple Cider)",
        "கோகோ பிஸ்கட் (Cocoa Biscuits)",
        "கார்ன் சிப்ஸ் (Corn Chips)",
        "டோர்டில்லா (Tortilla)",
        "சாசா (Salsa)",
        "பிக்கிள் மிக்ஸ் (Pickle Mix)",
        "சமையல் உபகரணம் (Kitchen Tools)",
        "மசாலா தேநீர் (Masala Tea Pack)",
        "அயில் ஸ்ப்ரே (Oil Spray)",
        "சமையல் உப்பு (Cooking Salt)",
        "அரிசி வல்லரி (Rice Sevai)",
        "எள்ளு (Sesame Seeds)",
        "எள்ளு உருண்டை (Sesame Balls)",
        "எள்ளெண்ணெய் (Sesame Oil)",
        "பனை ஓலை சர்க்கரை (Palm Sugar)",
        "கொத்துமல்லி விதை (Coriander Seeds)",
        "சீரக விதை (Cumin Seeds)",
        "மல்லி விதை (Coriander Whole)",
        "மிளகு முழு (Whole Pepper)",
        "சூப் பை (Soup Pack)",
        "தோசை கருவி (Dosa Tawa)",
        "அப்பம் பாத்திரம் (Appam Pan)",
        "இட்லி தட்டு (Idli Plate)",
        "குக்கர் (Pressure Cooker)",
        "நாண் ரோலர் (Rolling Pin)",
        "பேக்கிங் சோடா (Baking Soda)",
        "பேக்கிங் பவுடர் (Baking Powder)",
        "மக்காச்சோளம் மாவு (Corn Flour)",
        "மழை கோட் (Rain Coat)",
        "சில்வர் ஃபாயில் (Silver Foil)",
        "பிளாஸ்டிக் கப் (Plastic Cup)",
        "பேப்பர் கப் (Paper Cup)",
        "பேப்பர் தட்டு (Paper Plate)",
        "பாலக் சூப் (Palak Soup)",
        "தக்காளி சூப் (Tomato Soup)",
        "மசாலா நூடுல்ஸ் (Masala Noodles)",
        "மசாலா ஓட்ஸ் (Masala Oats)",
        "காய்கறி புலாவ் (Veg Pulao)",
        "பாஸ்தா மசாலா (Pasta Masala)",
        "சீஸ் மக்கரோனி (Cheese Macaroni)",
        "சமோசா (Samosa)",
        "பஜ்ஜி (Bajji)",
        "வடை (Vadai)",
        "பூரி (Poori)",
        "மசால் இட்லி (Masala Idli)",
        "உப்புமா (Upma)",
        "சேமியா பாயசம் (Semiya Payasam)",
        "அரிசி கஞ்சி (Rice Kanji)",
        "சட்னி (Chutney)",
        "தேங்காய் சட்னி (Coconut Chutney)",
        "மல்லி சட்னி (Coriander Chutney)",
        "புதினா சட்னி (Mint Chutney)",
        "மிளகாய் சட்னி (Chilli Chutney)",
        "தோசை மசாலா (Dosa Masala)",
        "சாம்பார் (Sambar)",
        "ரசம் (Rasam)",
        "குழம்பு (Kuzhambu)",
        "மோர் குழம்பு (Mor Kuzhambu)",
        "வத்தல் குழம்பு (Vathal Kuzhambu)",
        "அவியல் (Avial)",
        "கூட்டு (Kootu)",
        "பொரியல் (Poriyal)",
        "வருவல் (Varuval)",
        "சாதம் பொடி (Rice Powder)",
        "சீனி பொடி (Sugar Powder)",
        "எலுமிச்சை உப்பு (Lemon Salt)",
        "குறுமா (Kurma)",
        "சேவை வகை (Sevai Varieties)",
        "அத்தோ (Atho)",
        "பாயசம் (Payasam)",
        "ஜிலேபி (Jalebi)",
        "லட்டு (Laddu)",
        "மைசூர் பாக் (Mysore Pak)",
        "ஹல்வா (Halwa)",
        "மாங்காய் ஜூஸ் (Mango Juice)",
        "ஆப்பிள் ஜூஸ் (Apple Juice)",
        "திராட்சை ஜூஸ் (Grape Juice)",
        "குளிர்ச்சி லஸ்சி (Sweet Lassi)",
        "மசாலா லஸ்சி (Masala Lassi)",
        "பாதாம் சர்பத் (Badam Sharbat)",
        "ரோஸ் சர்பத் (Rose Sharbat)",
        "புதினா சர்பத் (Mint Sharbat)",
        "சோப்பு பொடி (Soap Powder)",
        "வாசனை திரவம் (Perfume)",
        "மவுத் ஃப்ரெஷனர் (Mouth Freshener)",
        "பூச்சு ரெபெல்லண்ட் (Mosquito Repellent)",
        "மாடி வாசனை (Floor Fragrance)",
        "கை துடைப்பான் (Hand Towels)",
        "சமைப்புக் கத்தி (Kitchen Knife)",
        "கிச்சன் ஸ்பாடுலா (Kitchen Spatula)",
        "ஸ்டீல் கப் (Steel Cup)",
        "ஸ்டீல் தட்டு (Steel Plate)",
        "ஸ்டீல் கரண்டி (Steel Spoon)",
        "பிளாஸ்டிக் பாட்டில் (Plastic Bottle)",
        "மண் குடம் (Clay Pot)",
        "மண் பானை (Clay Pan)",
        "ஸ்டீல் குடம் (Steel Pot)",
        "தீப்பெட்டி (Matchbox)",
        "மெழுகுவர்த்தி செட் (Candle Set)",
        "காப்பி பவுடர் (Instant Coffee)",
        "தேநீர் பாக்கெட் (Tea Bags)",
        "கிரீன் டீ (Green Tea)",
        "ப்ரௌன் ரைஸ் (Brown Rice)",
        "சேமியா நூடுல்ஸ் (Vermicelli Noodles)",
        "சோயா பீன்ஸ் (Soy Beans)",
        "ஆவல் அரிசி (Flattened Rice)",
        "பால் சேமியா (Milk Vermicelli)",
        "சீனி சர்க்கரை காடி (Sugar Candy Sticks)",
        "சில்வர் பட்டம் (Silver Leaves)",
        "கேனில் தண்ணீர் (Canned Water)",
        "பேக் செய்யப்பட்ட பால் (Tetra Milk)",
        "கழுவும் துணி (Dish Cloth)",
        "உடைகள் கழுவும் பொடி (Laundry Powder)",
        "முக கவசம் (Face Mask)",
        "கையுறைகள் (Disposable Gloves)",
        "சேனிட்டரி ஹேண்ட் ஜெல் (Hand Gel)",
        "குளியல் சோப்பு (Bath Soap)",
        "முடி ஆயில் (Hair Oil)",
        "பாட்டில் சோப்பு (Liquid Soap)",
        "முக அழகு கிரீம் (Beauty Cream)",
        "முக சுத்தி (Face Scrub)",
        "குடிநீர் (Drinking Water)",
        "குளிர்ச்சி பானம் (Cool Drink)",
        "பெருங்காயம் பவுடர் (Asafoetida Powder)",
        "கருப்பு மிளகு தூள் (Black Pepper Powder)",
        "காரமான சிப்ஸ் (Spicy Chips)",
        "பால்கோவா (Milk Peda)",
        "பால்வடை (Milk Vadai)",
        "சேமியா உப்புமா (Vermicelli Upma)",
        "சீனி பிஸ்கட் (Sweet Biscuits)",
        "கார பிஸ்கட் (Spicy Biscuits)",
    ]
    for name in extras:
        expanded.append((name, "Food & Beverages"))

random.shuffle(expanded)

for name, category in expanded:
    if len(products) >= target:
        break
    if name in existing:
        continue
    price = random.randint(20, 500)
    stock = random.randint(20, 200)
    doc = {
        "name": name,
        "category": category,
        "price": price,
        "variants": [
            {"size": "1kg", "stock": stock, "price": price},
            {"size": "500g", "stock": int(stock * 0.6), "price": int(price * 0.55)},
        ],
        "description": f"Fresh {name} - quality assured",
        "created_at": now,
        "updated_at": now,
    }
    products.append(doc)
    existing.add(name)

if len(products) < target:
    print(f"Only {len(products)} unique products generated. Add more names to reach 400.")
    sys.exit(1)

result = products_update.insert_many(products)
print(f"Inserted {len(result.inserted_ids)} NEW products into products_update")
